### ISSUE TITLE
Warnings in rich snippet

### ISSUE THREAD

**Issue by Vishakha-Patel** [Codeinwp/wp-product-review#412] opened 2019-05-27 12:02 UTC
Checking page in Google Structured data tool, shows warnings:

https://search.google.com/structured-data/testing-tool/u/0/?url=http://fpv.tv/jjrc-h20w-wifi-fpv-nano-quadcopter-for-android-and-apple/#url=https%3A%2F%2Fdemo.themeisle.com%2Fwp-product-review%2Fmultiple-review-templates%2F

They are not errors, just warnings.

Is there a way to avoid them? We receive ticket with this question.

Ticket: https://secure.helpscout.net/conversation/862122635/189793/

@contactashish13

**Comment by contactashish13** [comment] 2019-05-28 04:29
@Vishakha-Patel I don't see any warnings:

![image](https://user-images.githubusercontent.com/12953439/58451014-3ee2ae80-812f-11e9-8245-fb36c42e9397.png)

**Comment by Vishakha-Patel** [comment] 2019-05-28 11:12
@contactashish13 

That was the wrong URL. Sorry for that.

Here's correct one - https://search.google.com/structured-data/testing-tool/u/0/#url=https%3A%2F%2Fdemo.themeisle.com%2Fwp-product-review%2Ftemplate-1%2F

**Comment by contactashish13** [comment] 2019-05-28 13:40
@Vishakha-Patel The recently released version allows you to fill up all the fields relevant to the schema. Did you fill out all the fields for the Product schema type?

**Comment by Vishakha-Patel** [comment] 2019-05-30 07:14
@contactashish13 

After filling up all the fields too, there are four warnings for availability, priceValidUntil, url & aggregateRating.
https://www.dropbox.com/s/hl69dcorj630rij/Screenshot%202019-05-30%2012.41.09.png?dl=0

Also, the above URL in last comment is from our demo. It has 3 common warning as per my local test for for availability, priceValidUntil & url.

Is there any other settings needed?

**Comment by contactashish13** [comment] 2019-05-30 07:16
Please check the comment attached to the issue where I have mentioned why this occurs.

**Comment by Vishakha-Patel** [comment] 2019-06-04 13:16
@contactashish13 Checking this. Will update/close depending on the results.

**Comment by contactashish13** [comment] 2019-07-23 08:56
closing this as this is not a bug

**Closed by contactashish13** 2019-07-23 08:56 UTC
Labels: feedback
