### ISSUE TITLE
Review bar (slider) issue

### ISSUE THREAD

**Issue by mileamadalin** [Codeinwp/wp-product-review#99] opened 2016-05-24 09:56 UTC
@selu91 We have an issue: 

Review bar (slider) from comment section is not working as smooth as on PC desktop.

It doesn' allow the user to drag but hit on the somewhere, and cannot drag from the point you tap. 

Message from the client: 

"
you see the review comment form, with evaluating slider (scale 1~10, for total 4 categories),,which is working perfectly, as we wished.

However, if you see this page with iPhone, the slider doesn't work as the same as PC site.

You can't grab the ball (on the slider) and drag them but you have to tap somewhere on the bar instead.
"

ex: http://www.at-newyork-hotel.com/newyork_hotel011/four_seasons_hotel_ny-review.html

**Comment by selu91** [comment] 2016-05-24 10:19
@claudiuvertistudio can you check this please ?

**Comment by claudiuvertistudio** [comment] 2016-05-27 11:57
@mileamadalin This is not a bug. For this we need to use another library, jquer.mobile.js ( this is not included in wordpress, that means we cannot call with wp_enqueue_script ). 

@selu91 What do you thing, that effect is important on mobile?

**Comment by selu91** [comment] 2016-05-27 12:00
@claudiuvertistudio we can do the next thing, check if user is viewing on mobile: 

https://codex.wordpress.org/Function_Reference/wp_is_mobile 

And if yes, let enqueue the script for mobile. 

@ineagu what do you think about this  ?, will worth adding a new script just for the mobile users ?

**Comment by ineagu** [comment] 2016-05-27 13:56
@mileamadalin @selu91 This issue was reported previously, I analysed it and closed it, is too complex and isn't something that we should care so much, if works when you tap is perfectly fine.

**Closed by ineagu** 2016-05-27 13:56 UTC
Labels: bug
